[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/lazy-lifts/*"
  to = "/lazy-lifts/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin" 