[build]
  command = "npm run build"
  publish = ".next"

# For subdirectory deployment, uncomment these redirects
# [[redirects]]
#   from = "/lazy-lifts/*"
#   to = "/lazy-lifts/:splat"
#   status = 200

# This ensures all routes are handled by Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin" 